worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;

            on_publish http://host.docker.internal:9084/hooks/publish;
            on_publish_done http://host.docker.internal:9084/hooks/publish_done;

            deny play all;
        }
    }
}

http {
    server {
        listen 8088;
        location /health {
            return 200 "ok\n";
        }
    }
}
